/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import app.PapeleriaApp;


/**
 *
 * @author Eduardo
 */
public class Papeleria extends javax.swing.JFrame {

    PapeleriaApp app = new PapeleriaApp();
//    DefaultTableModel modelT; 
    TablaV wdgui = new TablaV();
            
    
    public void limpiarElementos(){
        
        this.textClave.setText("");
        this.textDescripcion.setText("");
        this.jLabel11.setText("0.00");
        this.textPrecioCompra.setText("");
        this.textPrecioVenta.setText("");
        this.txtIndice.setText("");
        this.JCcantidad.setSelectedIndex(0);
        this.JCNombreArticulo.setSelectedIndex(0);
        
    }
    
    //Variables 
  
//    
    
    
    
    /**
     * Creates new form PapeleriaApp
     */
    public Papeleria() {
        initComponents();
        limpiarElementos();
//        String encabezadoT[] = {"Inidice","Nombre Articulo","Clave","Descripcion","Cantidad","Precio Compra","Precio Venta","Ganancia"};
//        String datosT[][] = {};
//        modelT = new DefaultTableModel(datosT, encabezadoT);
//        this.Tabla.setModel(modelT);
        this.wdgui.setVisible(true);
        
    }

    public void agregar(){
        
       // this.wdgui.llenarTabla();
       this.wdgui.llenarTabla(this.txtIndice.getText(), this.JCNombreArticulo.getSelectedItem().toString(), this.textClave.getText(), this.textDescripcion.getText(), this.JCcantidad.getSelectedItem().toString(), Double.parseDouble(this.textPrecioCompra.getText()), Double.parseDouble(this.textPrecioVenta.getText()), Double.parseDouble(this.jLabel11.getText()));
       limpiarElementos();
       this.app.limpiarVar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        JCNombreArticulo = new javax.swing.JComboBox<>();
        textClave = new javax.swing.JTextField();
        textDescripcion = new javax.swing.JTextField();
        JCcantidad = new javax.swing.JComboBox<>();
        textPrecioCompra = new javax.swing.JTextField();
        textPrecioVenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("PAPELERIA \"EL RED\"");

        jLabel2.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Indice :");

        jLabel3.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombre Articulo :");

        jLabel4.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Clave :");

        jLabel5.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Descripcion :");

        jLabel6.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Catidad :");

        jLabel7.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Precio Compra :");

        jLabel8.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Precio Venta :");

        txtIndice.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        txtIndice.setForeground(new java.awt.Color(102, 102, 102));
        txtIndice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIndice.setText("jTextField1");

        JCNombreArticulo.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        JCNombreArticulo.setForeground(new java.awt.Color(102, 102, 102));
        JCNombreArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lapiz", "Goma", "Colores", "Libreta ", "Mochila", "Memoria USB", "Disco CD", "Pluma", "Lapizero", "Hoja de Color", "Hoja Blanca", "Plumon", " " }));

        textClave.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        textClave.setForeground(new java.awt.Color(102, 102, 102));
        textClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textClave.setText("jTextField2");

        textDescripcion.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        textDescripcion.setForeground(new java.awt.Color(102, 102, 102));
        textDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDescripcion.setText("jTextField3");

        JCcantidad.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        JCcantidad.setForeground(new java.awt.Color(102, 102, 102));
        JCcantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", " " }));

        textPrecioCompra.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        textPrecioCompra.setForeground(new java.awt.Color(102, 102, 102));
        textPrecioCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPrecioCompra.setText("jTextField4");

        textPrecioVenta.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        textPrecioVenta.setForeground(new java.awt.Color(102, 102, 102));
        textPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPrecioVenta.setText("jTextField5");

        jButton1.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("CALCULAR GANANCIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));

        jLabel10.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Ganancia :");

        jButton2.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 102));
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIndice)
                                    .addComponent(JCNombreArticulo, 0, 1, Short.MAX_VALUE)
                                    .addComponent(JCcantidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textClave)
                                    .addComponent(textDescripcion)
                                    .addComponent(textPrecioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(textPrecioVenta)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel11))
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JCNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JCcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.app.calcularGanacia(Double.parseDouble(this.textPrecioCompra.getText()), Double.parseDouble(this.textPrecioVenta.getText()),Integer.parseInt(this.JCcantidad.getSelectedItem().toString()));
        this.jLabel11.setText(String.valueOf(this.app.ganancia));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_jButton2ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCNombreArticulo;
    private javax.swing.JComboBox<String> JCcantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textClave;
    private javax.swing.JTextField textDescripcion;
    private javax.swing.JTextField textPrecioCompra;
    private javax.swing.JTextField textPrecioVenta;
    private javax.swing.JTextField txtIndice;
    // End of variables declaration//GEN-END:variables
}
