/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class TablaV extends javax.swing.JFrame  {

    DefaultTableModel modelT; 
   // Papeleria app = new Papeleria();
    
    /**
     * Creates new form TablaV
     */
    public TablaV() {
        initComponents();
        String encabezadoT[] = {"Inidice","Nombre Articulo","Clave","Descripcion","Cantidad","Precio Compra","Precio Venta","Ganancia"};
        String datosT[][] = {};
        modelT = new DefaultTableModel(datosT, encabezadoT);
        this.Tablet.setModel(modelT);
    }
    
    public void llenarTabla(String indice,String nombreArticulo,String clave,String descripcion,String cantidad,double precioCompra,double precioVenta,double ganancia){

          Object addDatos[] = {indice,nombreArticulo,clave,descripcion,cantidad,precioCompra,precioVenta,ganancia};
          this.modelT.addRow(addDatos);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tablet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Tabla de Productos");
        setResizable(false);

        Tablet.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        Tablet.setForeground(new java.awt.Color(102, 102, 102));
        Tablet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tablet);

        jLabel1.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Tabla de Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
